name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Secrets
        run: |
          mkdir -p .ssh
          echo "$SSH_PRIVATE_KEY" > .ssh/deploy
          sudo chmod 600 .ssh/deploy
          echo "$SSH_KNOWN_HOSTS" > .ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

      - name: Deploy
        run: ./01-scripts/deploy.sh
        shell: bash
